const Schema = {
    User: 'u',
    Router: 'r',
    Device: 'd',
    Stage: 's',
    Group: 'g',
    CustomGroupPosition: 'cgp',
    CustomGroupVolume: 'cgv',
    StageMember: 'sm',
    CustomStageMemberPosition: 'csmp',
    CustomStageMemberVolume: 'csmv',
    RemoteAudioTrack: 'a',
    CustomRemoteAudioTrackPosition: 'cap',
    CustomRemoteAudioTrackVolume: 'cav',
    RemoteVideoTrack: 'v',
    SoundCard: 'sc',
    // ChatMessage: "c",
    ChatMessage: 'c',
}
export default Schema
